name: build images

on:
  workflow_call:
  push:
    branches: [ "*", "**/*" ]

jobs:

  buildImages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.21'
  
    - name: Set up Docker context for Buildx
      id: buildx-context
      run: |
        docker context create builders
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        endpoint: builders

    - run: go mod vendor

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build images
      id: buildimages
      run: |
        img=ghcr.io/${{github.repository}}:${{github.sha}}
        make build
        make REGISTRY=ghcr.io/${{github.repository}} TAG=v1.5.1-${{github.sha}} image-chroot
        docker push ghcr.io/${{github.repository}}/controller-chroot:v1.5.1-${{github.sha}}
       